# This workflow will do a clean installation of node dependencies, setup credentials and secrets, and start the application when a PR is merged into master.

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Process Sermons CI

on:
  pull_request_target:
    types:
      - closed
    branches: [ "master" ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: create-json
        id: create-json-1
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: create-json
        id: create-json-2
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "token.json"
          json: ${{ secrets.ACCESS_TOKEN }}
      - run: touch .env && echo "${{ secrets.DOTENV }}" > .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start
